/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Ingredient, IngredientCheckDetail } from "./components/ingredient-list/ingredient-list";
import { MealDropDetail, MealSlotDetail } from "./components/meal-slot/meal-slot";
import { RatingChangeDetail } from "./components/rating-stars/rating-stars";
import { FavoriteToggleDetail, RecipeSelectDetail } from "./components/recipe-card/recipe-card";
import { SearchDetail } from "./components/recipe-search-bar/recipe-search-bar";
export { Ingredient, IngredientCheckDetail } from "./components/ingredient-list/ingredient-list";
export { MealDropDetail, MealSlotDetail } from "./components/meal-slot/meal-slot";
export { RatingChangeDetail } from "./components/rating-stars/rating-stars";
export { FavoriteToggleDetail, RecipeSelectDetail } from "./components/recipe-card/recipe-card";
export { SearchDetail } from "./components/recipe-search-bar/recipe-search-bar";
export namespace Components {
    /**
     * Renders an ingredient checklist.
     * `items` accepts either a real array (set as a DOM property, which is how
     * SvelteKit binds it) or a JSON string (useful from plain HTML). Parsing both
     * shapes keeps the component honest in either environment.
     */
    interface IngredientList {
        /**
          * When true each row gets a checkbox and emits `ingredientCheck`.
          * @default false
         */
        "checkable": boolean;
        /**
          * Renders the list in two columns on wide viewports.
          * @default false
         */
        "columns": boolean;
        /**
          * Heading text shown above the list.
          * @default 'Ingredients'
         */
        "heading": string;
        /**
          * Ingredients as an array of `{ name, measure }`, or a JSON string of the same.
          * @default []
         */
        "items": Ingredient[] | string;
    }
    /**
     * One cell of the weekly meal planner grid.
     * The slot is both a drop target (for drag-and-drop planning) and a plain
     * button (for click-to-assign), so the planner stays usable with a keyboard
     * and on touch devices where dragging is awkward.
     */
    interface MealSlot {
        /**
          * Day key, e.g. "Monday". Echoed back in every event.
         */
        "day": string;
        /**
          * MIME type read from the drag payload. Must match what the drag source sets.
          * @default 'text/recipe-id'
         */
        "dropMimeType": string;
        /**
          * Highlights the slot, e.g. for the current day.
          * @default false
         */
        "highlighted": boolean;
        /**
          * Meal key, e.g. "Breakfast". Echoed back in every event.
         */
        "meal": string;
        /**
          * Id of the assigned recipe. Leave unset to render the empty state.
         */
        "recipeId"?: string;
        /**
          * Thumbnail of the assigned recipe.
         */
        "recipeImage"?: string;
        /**
          * Secondary line under the title, e.g. the category.
         */
        "recipeMeta"?: string;
        /**
          * Title of the assigned recipe.
         */
        "recipeName"?: string;
    }
    /**
     * An accessible modal built on the native `<dialog>` element.
     * Delegating to `<dialog>` buys focus trapping, the top layer, inert background
     * content and Escape handling from the platform rather than re-implementing
     * them. `open` stays the source of truth: closing always routes through
     * `dialogClose` so the consumer's state and the DOM cannot drift apart.
     */
    interface ModalDialog {
        /**
          * Text of the default heading.
          * @default ''
         */
        "heading": string;
        /**
          * Hides the built-in close button, e.g. for a forced choice.
          * @default false
         */
        "hideClose": boolean;
        /**
          * Controls visibility. The component never flips this itself.
          * @default false
         */
        "open": boolean;
        /**
          * When true, clicking the backdrop does not request a close.
          * @default false
         */
        "persistent": boolean;
        /**
          * Imperatively request a close, emitting `dialogClose`.
         */
        "requestClose": () => Promise<void>;
        /**
          * Supporting line under the heading.
          * @default ''
         */
        "subheading": string;
        /**
          * Max width of the dialog panel, as any CSS length.
          * @default '560px'
         */
        "width": string;
    }
    /**
     * A star rating that works as either a read-only indicator or an input.
     * When `readonly` is false the control is keyboard operable: arrow keys move
     * between values and Home/End jump to the ends, matching the ARIA slider
     * pattern that assistive technology already knows.
     */
    interface RatingStars {
        /**
          * Accessible label for the control.
          * @default 'Rating'
         */
        "label": string;
        /**
          * Number of stars to render.
          * @default 5
         */
        "max": number;
        /**
          * When true the stars are a display-only indicator.
          * @default false
         */
        "readonly": boolean;
        /**
          * Renders the numeric value next to the stars.
          * @default false
         */
        "showValue": boolean;
        /**
          * Star edge size in pixels.
          * @default 16
         */
        "size": number;
        /**
          * Current rating. Fractional values render partially filled stars.
          * @default 0
         */
        "value": number;
    }
    /**
     * A presentational card summarising a single recipe.
     * The component owns no state: `favorite` is controlled by the consumer, which
     * reacts to `favoriteToggle` and passes the new value back down. That keeps the
     * card usable from any framework without fighting over who owns the truth.
     */
    interface RecipeCard {
        /**
          * Cuisine or region label, e.g. "Italian".
         */
        "area"?: string;
        /**
          * Marks the recipe as user-created, which surfaces an "Own recipe" chip.
          * @default false
         */
        "authored": boolean;
        /**
          * Category label, e.g. "Dessert". Rendered as the primary meta chip.
         */
        "category"?: string;
        /**
          * Renders a slimmer layout for dense grids and planner columns.
          * @default false
         */
        "compact": boolean;
        /**
          * Whether the recipe is currently in the user's favorites.
          * @default false
         */
        "favorite": boolean;
        /**
          * Absolute or relative URL of the recipe image.
         */
        "image"?: string;
        /**
          * Recipe title shown as the card heading.
         */
        "name": string;
        /**
          * Optional 0-5 rating. Omit or set to 0 to hide the stars.
          * @default 0
         */
        "rating": number;
        /**
          * Stable identifier passed back in every emitted event.
         */
        "recipeId": string;
        /**
          * Comma-separated tag list, e.g. "Pasta,Quick". Blank entries are ignored.
         */
        "tags"?: string;
    }
    /**
     * A debounced search field with an optional filter tray.
     * Two events are emitted deliberately: `searchInput` fires on every debounced
     * keystroke so a consumer can drive live results, while `searchSubmit` fires
     * only on Enter or the button. Consumers pick whichever suits their API budget.
     */
    interface RecipeSearchBar {
        /**
          * Milliseconds to wait after the last keystroke before emitting `searchInput`.
          * @default 350
         */
        "debounce": number;
        /**
          * Disables the whole control.
          * @default false
         */
        "disabled": boolean;
        /**
          * Shows a spinner in place of the search icon.
          * @default false
         */
        "loading": boolean;
        /**
          * Placeholder text for the input.
          * @default 'Search recipes...'
         */
        "placeholder": string;
        /**
          * Text of the submit button. Set to an empty string to hide the button.
          * @default 'Search'
         */
        "submitLabel": string;
        /**
          * Controlled value. Updating it from the consumer resets the internal draft.
          * @default ''
         */
        "value": string;
    }
}
export interface IngredientListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIngredientListElement;
}
export interface MealSlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealSlotElement;
}
export interface ModalDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModalDialogElement;
}
export interface RatingStarsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRatingStarsElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface RecipeSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeSearchBarElement;
}
declare global {
    interface HTMLIngredientListElementEventMap {
        "ingredientCheck": IngredientCheckDetail;
    }
    /**
     * Renders an ingredient checklist.
     * `items` accepts either a real array (set as a DOM property, which is how
     * SvelteKit binds it) or a JSON string (useful from plain HTML). Parsing both
     * shapes keeps the component honest in either environment.
     */
    interface HTMLIngredientListElement extends Components.IngredientList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIngredientListElementEventMap>(type: K, listener: (this: HTMLIngredientListElement, ev: IngredientListCustomEvent<HTMLIngredientListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIngredientListElementEventMap>(type: K, listener: (this: HTMLIngredientListElement, ev: IngredientListCustomEvent<HTMLIngredientListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIngredientListElement: {
        prototype: HTMLIngredientListElement;
        new (): HTMLIngredientListElement;
    };
    interface HTMLMealSlotElementEventMap {
        "mealAssign": MealSlotDetail;
        "mealRemove": MealSlotDetail;
        "mealOpen": MealSlotDetail;
        "mealDrop": MealDropDetail;
    }
    /**
     * One cell of the weekly meal planner grid.
     * The slot is both a drop target (for drag-and-drop planning) and a plain
     * button (for click-to-assign), so the planner stays usable with a keyboard
     * and on touch devices where dragging is awkward.
     */
    interface HTMLMealSlotElement extends Components.MealSlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealSlotElementEventMap>(type: K, listener: (this: HTMLMealSlotElement, ev: MealSlotCustomEvent<HTMLMealSlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealSlotElementEventMap>(type: K, listener: (this: HTMLMealSlotElement, ev: MealSlotCustomEvent<HTMLMealSlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealSlotElement: {
        prototype: HTMLMealSlotElement;
        new (): HTMLMealSlotElement;
    };
    interface HTMLModalDialogElementEventMap {
        "dialogClose": void;
        "dialogOpen": void;
    }
    /**
     * An accessible modal built on the native `<dialog>` element.
     * Delegating to `<dialog>` buys focus trapping, the top layer, inert background
     * content and Escape handling from the platform rather than re-implementing
     * them. `open` stays the source of truth: closing always routes through
     * `dialogClose` so the consumer's state and the DOM cannot drift apart.
     */
    interface HTMLModalDialogElement extends Components.ModalDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModalDialogElementEventMap>(type: K, listener: (this: HTMLModalDialogElement, ev: ModalDialogCustomEvent<HTMLModalDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModalDialogElementEventMap>(type: K, listener: (this: HTMLModalDialogElement, ev: ModalDialogCustomEvent<HTMLModalDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModalDialogElement: {
        prototype: HTMLModalDialogElement;
        new (): HTMLModalDialogElement;
    };
    interface HTMLRatingStarsElementEventMap {
        "ratingChange": RatingChangeDetail;
    }
    /**
     * A star rating that works as either a read-only indicator or an input.
     * When `readonly` is false the control is keyboard operable: arrow keys move
     * between values and Home/End jump to the ends, matching the ARIA slider
     * pattern that assistive technology already knows.
     */
    interface HTMLRatingStarsElement extends Components.RatingStars, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRatingStarsElementEventMap>(type: K, listener: (this: HTMLRatingStarsElement, ev: RatingStarsCustomEvent<HTMLRatingStarsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRatingStarsElementEventMap>(type: K, listener: (this: HTMLRatingStarsElement, ev: RatingStarsCustomEvent<HTMLRatingStarsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRatingStarsElement: {
        prototype: HTMLRatingStarsElement;
        new (): HTMLRatingStarsElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "recipeSelect": RecipeSelectDetail;
        "favoriteToggle": FavoriteToggleDetail;
    }
    /**
     * A presentational card summarising a single recipe.
     * The component owns no state: `favorite` is controlled by the consumer, which
     * reacts to `favoriteToggle` and passes the new value back down. That keeps the
     * card usable from any framework without fighting over who owns the truth.
     */
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeSearchBarElementEventMap {
        "searchInput": SearchDetail;
        "searchSubmit": SearchDetail;
        "searchClear": void;
    }
    /**
     * A debounced search field with an optional filter tray.
     * Two events are emitted deliberately: `searchInput` fires on every debounced
     * keystroke so a consumer can drive live results, while `searchSubmit` fires
     * only on Enter or the button. Consumers pick whichever suits their API budget.
     */
    interface HTMLRecipeSearchBarElement extends Components.RecipeSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeSearchBarElementEventMap>(type: K, listener: (this: HTMLRecipeSearchBarElement, ev: RecipeSearchBarCustomEvent<HTMLRecipeSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeSearchBarElementEventMap>(type: K, listener: (this: HTMLRecipeSearchBarElement, ev: RecipeSearchBarCustomEvent<HTMLRecipeSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeSearchBarElement: {
        prototype: HTMLRecipeSearchBarElement;
        new (): HTMLRecipeSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "ingredient-list": HTMLIngredientListElement;
        "meal-slot": HTMLMealSlotElement;
        "modal-dialog": HTMLModalDialogElement;
        "rating-stars": HTMLRatingStarsElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-search-bar": HTMLRecipeSearchBarElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * Renders an ingredient checklist.
     * `items` accepts either a real array (set as a DOM property, which is how
     * SvelteKit binds it) or a JSON string (useful from plain HTML). Parsing both
     * shapes keeps the component honest in either environment.
     */
    interface IngredientList {
        /**
          * When true each row gets a checkbox and emits `ingredientCheck`.
          * @default false
         */
        "checkable"?: boolean;
        /**
          * Renders the list in two columns on wide viewports.
          * @default false
         */
        "columns"?: boolean;
        /**
          * Heading text shown above the list.
          * @default 'Ingredients'
         */
        "heading"?: string;
        /**
          * Ingredients as an array of `{ name, measure }`, or a JSON string of the same.
          * @default []
         */
        "items"?: Ingredient[] | string;
        /**
          * Fired when a checkable row is toggled.
         */
        "onIngredientCheck"?: (event: IngredientListCustomEvent<IngredientCheckDetail>) => void;
    }
    /**
     * One cell of the weekly meal planner grid.
     * The slot is both a drop target (for drag-and-drop planning) and a plain
     * button (for click-to-assign), so the planner stays usable with a keyboard
     * and on touch devices where dragging is awkward.
     */
    interface MealSlot {
        /**
          * Day key, e.g. "Monday". Echoed back in every event.
         */
        "day": string;
        /**
          * MIME type read from the drag payload. Must match what the drag source sets.
          * @default 'text/recipe-id'
         */
        "dropMimeType"?: string;
        /**
          * Highlights the slot, e.g. for the current day.
          * @default false
         */
        "highlighted"?: boolean;
        /**
          * Meal key, e.g. "Breakfast". Echoed back in every event.
         */
        "meal": string;
        /**
          * Fired when an empty slot is activated, asking the host to open a picker.
         */
        "onMealAssign"?: (event: MealSlotCustomEvent<MealSlotDetail>) => void;
        /**
          * Fired when a recipe is dropped onto the slot.
         */
        "onMealDrop"?: (event: MealSlotCustomEvent<MealDropDetail>) => void;
        /**
          * Fired when a filled slot's body is activated, to open the recipe.
         */
        "onMealOpen"?: (event: MealSlotCustomEvent<MealSlotDetail>) => void;
        /**
          * Fired when the remove button on a filled slot is activated.
         */
        "onMealRemove"?: (event: MealSlotCustomEvent<MealSlotDetail>) => void;
        /**
          * Id of the assigned recipe. Leave unset to render the empty state.
         */
        "recipeId"?: string;
        /**
          * Thumbnail of the assigned recipe.
         */
        "recipeImage"?: string;
        /**
          * Secondary line under the title, e.g. the category.
         */
        "recipeMeta"?: string;
        /**
          * Title of the assigned recipe.
         */
        "recipeName"?: string;
    }
    /**
     * An accessible modal built on the native `<dialog>` element.
     * Delegating to `<dialog>` buys focus trapping, the top layer, inert background
     * content and Escape handling from the platform rather than re-implementing
     * them. `open` stays the source of truth: closing always routes through
     * `dialogClose` so the consumer's state and the DOM cannot drift apart.
     */
    interface ModalDialog {
        /**
          * Text of the default heading.
          * @default ''
         */
        "heading"?: string;
        /**
          * Hides the built-in close button, e.g. for a forced choice.
          * @default false
         */
        "hideClose"?: boolean;
        /**
          * Fired whenever a close is requested: button, Escape, or backdrop click.
         */
        "onDialogClose"?: (event: ModalDialogCustomEvent<void>) => void;
        /**
          * Fired once the dialog has finished opening.
         */
        "onDialogOpen"?: (event: ModalDialogCustomEvent<void>) => void;
        /**
          * Controls visibility. The component never flips this itself.
          * @default false
         */
        "open"?: boolean;
        /**
          * When true, clicking the backdrop does not request a close.
          * @default false
         */
        "persistent"?: boolean;
        /**
          * Supporting line under the heading.
          * @default ''
         */
        "subheading"?: string;
        /**
          * Max width of the dialog panel, as any CSS length.
          * @default '560px'
         */
        "width"?: string;
    }
    /**
     * A star rating that works as either a read-only indicator or an input.
     * When `readonly` is false the control is keyboard operable: arrow keys move
     * between values and Home/End jump to the ends, matching the ARIA slider
     * pattern that assistive technology already knows.
     */
    interface RatingStars {
        /**
          * Accessible label for the control.
          * @default 'Rating'
         */
        "label"?: string;
        /**
          * Number of stars to render.
          * @default 5
         */
        "max"?: number;
        /**
          * Fired when an interactive rating is changed by click or keyboard.
         */
        "onRatingChange"?: (event: RatingStarsCustomEvent<RatingChangeDetail>) => void;
        /**
          * When true the stars are a display-only indicator.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Renders the numeric value next to the stars.
          * @default false
         */
        "showValue"?: boolean;
        /**
          * Star edge size in pixels.
          * @default 16
         */
        "size"?: number;
        /**
          * Current rating. Fractional values render partially filled stars.
          * @default 0
         */
        "value"?: number;
    }
    /**
     * A presentational card summarising a single recipe.
     * The component owns no state: `favorite` is controlled by the consumer, which
     * reacts to `favoriteToggle` and passes the new value back down. That keeps the
     * card usable from any framework without fighting over who owns the truth.
     */
    interface RecipeCard {
        /**
          * Cuisine or region label, e.g. "Italian".
         */
        "area"?: string;
        /**
          * Marks the recipe as user-created, which surfaces an "Own recipe" chip.
          * @default false
         */
        "authored"?: boolean;
        /**
          * Category label, e.g. "Dessert". Rendered as the primary meta chip.
         */
        "category"?: string;
        /**
          * Renders a slimmer layout for dense grids and planner columns.
          * @default false
         */
        "compact"?: boolean;
        /**
          * Whether the recipe is currently in the user's favorites.
          * @default false
         */
        "favorite"?: boolean;
        /**
          * Absolute or relative URL of the recipe image.
         */
        "image"?: string;
        /**
          * Recipe title shown as the card heading.
         */
        "name": string;
        /**
          * Fired when the favorite button is activated.
         */
        "onFavoriteToggle"?: (event: RecipeCardCustomEvent<FavoriteToggleDetail>) => void;
        /**
          * Fired when the card body or its primary button is activated.
         */
        "onRecipeSelect"?: (event: RecipeCardCustomEvent<RecipeSelectDetail>) => void;
        /**
          * Optional 0-5 rating. Omit or set to 0 to hide the stars.
          * @default 0
         */
        "rating"?: number;
        /**
          * Stable identifier passed back in every emitted event.
         */
        "recipeId": string;
        /**
          * Comma-separated tag list, e.g. "Pasta,Quick". Blank entries are ignored.
         */
        "tags"?: string;
    }
    /**
     * A debounced search field with an optional filter tray.
     * Two events are emitted deliberately: `searchInput` fires on every debounced
     * keystroke so a consumer can drive live results, while `searchSubmit` fires
     * only on Enter or the button. Consumers pick whichever suits their API budget.
     */
    interface RecipeSearchBar {
        /**
          * Milliseconds to wait after the last keystroke before emitting `searchInput`.
          * @default 350
         */
        "debounce"?: number;
        /**
          * Disables the whole control.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Shows a spinner in place of the search icon.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Fired when the clear button empties the field.
         */
        "onSearchClear"?: (event: RecipeSearchBarCustomEvent<void>) => void;
        /**
          * Fired after the debounce window closes on each edit.
         */
        "onSearchInput"?: (event: RecipeSearchBarCustomEvent<SearchDetail>) => void;
        /**
          * Fired when the user presses Enter or activates the submit button.
         */
        "onSearchSubmit"?: (event: RecipeSearchBarCustomEvent<SearchDetail>) => void;
        /**
          * Placeholder text for the input.
          * @default 'Search recipes...'
         */
        "placeholder"?: string;
        /**
          * Text of the submit button. Set to an empty string to hide the button.
          * @default 'Search'
         */
        "submitLabel"?: string;
        /**
          * Controlled value. Updating it from the consumer resets the internal draft.
          * @default ''
         */
        "value"?: string;
    }

    interface IngredientListAttributes {
        "items": Ingredient[] | string;
        "heading": string;
        "checkable": boolean;
        "columns": boolean;
    }
    interface MealSlotAttributes {
        "day": string;
        "meal": string;
        "recipeId": string;
        "recipeName": string;
        "recipeImage": string;
        "recipeMeta": string;
        "highlighted": boolean;
        "dropMimeType": string;
    }
    interface ModalDialogAttributes {
        "open": boolean;
        "heading": string;
        "subheading": string;
        "hideClose": boolean;
        "persistent": boolean;
        "width": string;
    }
    interface RatingStarsAttributes {
        "value": number;
        "max": number;
        "readonly": boolean;
        "label": string;
        "showValue": boolean;
        "size": number;
    }
    interface RecipeCardAttributes {
        "recipeId": string;
        "name": string;
        "image": string;
        "category": string;
        "area": string;
        "tags": string;
        "favorite": boolean;
        "rating": number;
        "authored": boolean;
        "compact": boolean;
    }
    interface RecipeSearchBarAttributes {
        "placeholder": string;
        "value": string;
        "debounce": number;
        "submitLabel": string;
        "loading": boolean;
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "ingredient-list": Omit<IngredientList, keyof IngredientListAttributes> & { [K in keyof IngredientList & keyof IngredientListAttributes]?: IngredientList[K] } & { [K in keyof IngredientList & keyof IngredientListAttributes as `attr:${K}`]?: IngredientListAttributes[K] } & { [K in keyof IngredientList & keyof IngredientListAttributes as `prop:${K}`]?: IngredientList[K] };
        "meal-slot": Omit<MealSlot, keyof MealSlotAttributes> & { [K in keyof MealSlot & keyof MealSlotAttributes]?: MealSlot[K] } & { [K in keyof MealSlot & keyof MealSlotAttributes as `attr:${K}`]?: MealSlotAttributes[K] } & { [K in keyof MealSlot & keyof MealSlotAttributes as `prop:${K}`]?: MealSlot[K] } & OneOf<"day", MealSlot["day"], MealSlotAttributes["day"]> & OneOf<"meal", MealSlot["meal"], MealSlotAttributes["meal"]>;
        "modal-dialog": Omit<ModalDialog, keyof ModalDialogAttributes> & { [K in keyof ModalDialog & keyof ModalDialogAttributes]?: ModalDialog[K] } & { [K in keyof ModalDialog & keyof ModalDialogAttributes as `attr:${K}`]?: ModalDialogAttributes[K] } & { [K in keyof ModalDialog & keyof ModalDialogAttributes as `prop:${K}`]?: ModalDialog[K] };
        "rating-stars": Omit<RatingStars, keyof RatingStarsAttributes> & { [K in keyof RatingStars & keyof RatingStarsAttributes]?: RatingStars[K] } & { [K in keyof RatingStars & keyof RatingStarsAttributes as `attr:${K}`]?: RatingStarsAttributes[K] } & { [K in keyof RatingStars & keyof RatingStarsAttributes as `prop:${K}`]?: RatingStars[K] };
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] } & OneOf<"recipeId", RecipeCard["recipeId"], RecipeCardAttributes["recipeId"]> & OneOf<"name", RecipeCard["name"], RecipeCardAttributes["name"]>;
        "recipe-search-bar": Omit<RecipeSearchBar, keyof RecipeSearchBarAttributes> & { [K in keyof RecipeSearchBar & keyof RecipeSearchBarAttributes]?: RecipeSearchBar[K] } & { [K in keyof RecipeSearchBar & keyof RecipeSearchBarAttributes as `attr:${K}`]?: RecipeSearchBarAttributes[K] } & { [K in keyof RecipeSearchBar & keyof RecipeSearchBarAttributes as `prop:${K}`]?: RecipeSearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Renders an ingredient checklist.
             * `items` accepts either a real array (set as a DOM property, which is how
             * SvelteKit binds it) or a JSON string (useful from plain HTML). Parsing both
             * shapes keeps the component honest in either environment.
             */
            "ingredient-list": LocalJSX.IntrinsicElements["ingredient-list"] & JSXBase.HTMLAttributes<HTMLIngredientListElement>;
            /**
             * One cell of the weekly meal planner grid.
             * The slot is both a drop target (for drag-and-drop planning) and a plain
             * button (for click-to-assign), so the planner stays usable with a keyboard
             * and on touch devices where dragging is awkward.
             */
            "meal-slot": LocalJSX.IntrinsicElements["meal-slot"] & JSXBase.HTMLAttributes<HTMLMealSlotElement>;
            /**
             * An accessible modal built on the native `<dialog>` element.
             * Delegating to `<dialog>` buys focus trapping, the top layer, inert background
             * content and Escape handling from the platform rather than re-implementing
             * them. `open` stays the source of truth: closing always routes through
             * `dialogClose` so the consumer's state and the DOM cannot drift apart.
             */
            "modal-dialog": LocalJSX.IntrinsicElements["modal-dialog"] & JSXBase.HTMLAttributes<HTMLModalDialogElement>;
            /**
             * A star rating that works as either a read-only indicator or an input.
             * When `readonly` is false the control is keyboard operable: arrow keys move
             * between values and Home/End jump to the ends, matching the ARIA slider
             * pattern that assistive technology already knows.
             */
            "rating-stars": LocalJSX.IntrinsicElements["rating-stars"] & JSXBase.HTMLAttributes<HTMLRatingStarsElement>;
            /**
             * A presentational card summarising a single recipe.
             * The component owns no state: `favorite` is controlled by the consumer, which
             * reacts to `favoriteToggle` and passes the new value back down. That keeps the
             * card usable from any framework without fighting over who owns the truth.
             */
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            /**
             * A debounced search field with an optional filter tray.
             * Two events are emitted deliberately: `searchInput` fires on every debounced
             * keystroke so a consumer can drive live results, while `searchSubmit` fires
             * only on Enter or the button. Consumers pick whichever suits their API budget.
             */
            "recipe-search-bar": LocalJSX.IntrinsicElements["recipe-search-bar"] & JSXBase.HTMLAttributes<HTMLRecipeSearchBarElement>;
        }
    }
}
